#' @title Read metadata from a GT3X file
#' 
#' @description Read the metadata from a GT3X file as a data.frame.
#' @details Given a complete path to a file with extension ".gt3x" (exported from Actilife's software), import it's internal "info.txt" file, extract it's metadata and format it into an R data.frame.
#' @param origin path to a GT3X file from which to read the metadata
#' @param verbose logical: wether to show detailed log messages or not (default: FALSE)
#' @importFrom tidyr separate spread
#' @importFrom dplyr rename_all mutate_at vars
#' @importFrom magrittr divide_by %>%
#' @export
read_info <- function(origin, verbose = FALSE) {
  # Connection to the info.txt file:
  info <- unz(origin, filename = "info.txt")

  # Close the connection after quitting this function:
  on.exit(close(info))
    
  # Read in the file, format it and return it:
  data.frame(key = info %>% 
                     readLines) %>%
    # Breaking the lines into variables:
    separate(key, c("key", "value"), ": ") %>%
    # Changing to wide format:
    spread(key, value) %>%
    # Renaming all columns:
    rename_all(make.names) %>%
    # Formatting dates properly:
    mutate_at(vars(Download.Date,
                   Last.Sample.Time,
                   Start.Date,
                   Stop.Date),
              . %>%
                as.numeric %>%
                divide_by(1e7) %>%
                as.POSIXct(origin = "0001-01-01", tz = "UTC"))
}

#' @title Export GT3X metadata to CSV 
#' 
#' @description Formats the data.frame obtained from the read_info function into Actilife's header format, then exports it to a CSV file.
#'
#' @details Saves the header extracted from the .gt3x file with the read_info function in the .csv extension (look at read_info function)
#' @param df_file data.frame with metadata generated by the read_info function
#' @param outfile_csv  complete path to the output CSV file the header will be written to
#' @param verbose logical: wether to show detailed log messages or not (default: FALSE)
#' @importFrom hms as_hms
#' @importFrom stringr str_sub
#' @importFrom magrittr %>%
#' @importFrom logger log_trace
#' @export
save_header <- function(df_file, outfile_csv, verbose = FALSE){
  # Formatting metadata to Actilife's header format:
  if(verbose){
    log_trace("Formatting metadata to Actilife's header format.")
  }
  
  header_txt <- paste0("------------ Data File Created By ActiGraph GT3X+ ActiLife v6.13.4 Firmware v1.9.2 date format dd/MM/yyyy at 30 Hz  Filter Normal -----------\n",
                       "Serial Number: ", df_file$Serial.Number, "\n",
                       "Start Time ", df_file$Start.Date %>%
                                        str_sub(12, 20) %>%
                                        as_hms, "\n",
                       "Start Date ", format(df_file$Start.Date, "%d/%m/%Y"), "\n",
                       "Epoch Period (hh:mm:ss) 00:00:00\n",
                       "Download Time ", df_file$Download.Date %>%
                                           str_sub(12, 20) %>%
                                           as_hms, "\n",
                       "Download Date ", format(df_file$Download.Date, "%d/%m/%Y"), "\n",
                       "Current Memory Address: 0\n",
                       "Current Battery Voltage: ", sub(",", ".", df_file$Battery.Voltage),"     Mode = 12\n",
                       "--------------------------------------------------\n")
  
  # Writing the .csv document with the header
  if(verbose){
    log_trace("Exporting header information to '", outfile_csv, "'.")
  }
  
  cat(header_txt,
      file = outfile_csv)
}

#' @title GT3X header to Actilife's format
#' 
#' @description Reads metadata from ``.gt3x`` files, formats it to Actilife's standard format (for compatibility with GGIR) and exports it to a CSV file.
#' 
#' @details Reads the metadata from a GT3X file's internal "info.txt" file using the read_info function, then exports it as the header to a CSV file using the save_header function.
#' @param origin path to a GT3X file to convert
#' @param outdir path for outputting the CSV formatted file
#' @param verbose logical: wether to show detailed log messages or not (default: FALSE)
#' @importFrom stringr str_sub str_trim
#' @importFrom magrittr %>%
#' @importFrom logger log_trace log_info log_success
#' @export
header_csv <- function(origin, outdir, verbose = FALSE){
  # Input file:
  file <- basename(origin) %>%
            str_sub(1, -6)
  
  # Output directory:
  outdir_csv <- paste0(str_trim(outdir), "/csv")
  
  # Output file:
  outfile_csv <- paste0(outdir_csv, "/", file, "RAW.csv")
  
  # Create output directory if it doesn't already exist:
  if(!dir.exists(outdir_csv)){
    dir.create(outdir_csv)
    log_info("Output directory '", outdir_csv, "' created.")
  }else if(file.exists(outfile_csv)){
    log_info("File '", outdir_csv, "/", outfile_csv, "' already exists. Specify 'overwrite = FALSE' if you wish to skip such cases.")
  }
  
  # Reading info.txt file and formatting it as a dataframe:
  if(verbose){
    log_trace("Reading 'info.txt' file from '", origin, "'.")
  }
  
  info_filedf <- read_info(origin, verbose = verbose)
  
  # Trace message:
  if(verbose){
    log_success("Read 'info.txt' file, exporting it in CSV format.")
  }
  
  # Exporting header information as a CSV file:
  save_header(df_file = info_filedf, outfile_csv = outfile_csv, verbose = verbose)
  
  if(verbose){
    log_success("Exported header information to '", outfile_csv, "'.")
  }
}

#' @title Export GT3X contents
#' 
#' @description  Converts acceleration data from a ".gt3x" file to a data.frame and exports it to CSV.
#' 
#' @details This function reads the binary data inside the ".gt3x" file's internal "log.bin" file and saves it in CSV format.
#' @param acc.file path to a GT3X file to convert
#' @param outdir path for outputting the CSV formatted file (default: NULL). There will be another directory created inside this one, called "/csv".
#' @param verbose logical: wether to show detailed log messages or not (default: FALSE)
#' @importFrom read.gt3x read.gt3x
#' @importFrom stringr str_sub
#' @importFrom vroom vroom_write
#' @importFrom magrittr %>%
#' @importFrom logger log_trace log_success
#' @importFrom dplyr transmute
#' @importFrom data.table as.data.table
#' @export
save_accel <- function(acc.file, outdir = NULL, verbose = FALSE){
  # Initializing runtime counter:
  t_accel <- Sys.time()
  
  # Trace message:
  if(verbose){
    log_trace("Reading accelerometer information from '", acc.file, "'.")
  }
  
  # Filename:
  file_id <- basename(acc.file) %>% str_sub(1, -6)

  # Output CSV file:
  csv_file <- paste0(ifelse(is.null(outdir),
                            dirname(acc.file),
                            outdir),
                     "/csv/", file_id, "RAW.csv")
  
  # Reading accelerometer data and processing variables:
  accel_df <- read.gt3x(acc.file,
                        imputeZeroes = TRUE) %>%
                # Here, we drop the 'timestamp' column:
                as.data.table(.[, -4]) %>%
                transmute(`Accelerometer X` = Y %>% as.character,
                          `Accelerometer Y` = X %>% as.character,
                          `Accelerometer Z` = Z %>% as.character)
  
  # Writing acceleration data in csv:
  if(verbose){
    log_success("Read accelerometer data from '", file_id, ".gt3x:log.bin'. Took ", 
                (Sys.time() - t_accel) %>% as.numeric %>% round(2),
                " seconds.")
    log_trace("Appending accelerometer information to '", csv_file, "'.")
  }

  vroom_write(x = accel_df,
              path = csv_file, 
              append = TRUE,
              delim = ",",
              col_names = TRUE)
  
  if(verbose){
    log_success("Exported all information from '", file_id, ".gt3x' successfully. Took ",
                (Sys.time() - t_accel) %>% as.numeric %>% round(2),
                " seconds.")
  }
}

#' @title Export GT3X as CSV
#' 
#' @description Convert GT3X files to CSV format in Actilife's default export format.
#' 
#' @details Reads the "info.txt" and "log.bin" internal files from a ".gt3x" file exporter by Actilife's software and converts it to a CSV file in the same format of the CSV file extracted from the software.
#' @param gt3x_file path to a GT3X file to convert
#' @param outdir path for outputting the CSV formatted file (default: NULL). There will be another directory created inside this one, called "/csv".
#' @param verbose logical: wether to show detailed log messages or not (default: FALSE)
#' @export
#' @importFrom magrittr %>%
#' @importFrom utils unzip
#' @importFrom stringr str_sub str_detect
#' @importFrom logger log_layout layout_glue_colors log_threshold TRACE log_error log_trace log_info
#' @seealso gt3x_folder_2_csv converts a folder 
#' @seealso gt3x_2_csv_par converts a a folder using paralell processing
gt3x_2_csv <- function(gt3x_file = NULL, outdir = NULL, verbose = FALSE){
  # Configuring logger:
  log_layout(layout_glue_colors)
  log_threshold(TRACE)
  
  # Setting up error messages:
  #   - Made it so that all errors found are printed, to ease debugging
  quit <- FALSE
  
  #   - If there's no specified .gt3x file:
  if(is.null(gt3x_file)){
    quit <- TRUE
    log_error("Please specify a GT3X file with 'gt3x_file' in the function call.")
  #   - If the specified .gt3x file doesn't exist:
  } else if(!file.exists(gt3x_file)){
    #   - If even pasting the extension on it doesn't work, quit with an error:
    if(!file.exists(paste0(gt3x_file, ".gt3x"))){
      quit <- TRUE
      log_error("File '", gt3x_file, "' not found.")
    #   - Else, append the extension and keep going:
    } else{
      if(verbose){
        log_trace("File '", gt3x_file, "' not found. Using '", paste0(gt3x_file, ".gt3x"), "' as the filename.")
      }
      gt3x_file <- paste0(gt3x_file, ".gt3x")
    }
  } 
  
  #   - Checking for expected files inside the .gt3x:
  if(!"info.txt" %in% unzip(gt3x_file, list = TRUE)$Name |
     !"log.bin" %in% unzip(gt3x_file, list = TRUE)$Name){
    quit <- TRUE
    log_error("File '", gt3x_file, "' doesn't contain expected files within it.")
  }
  
  #   - If outdir is specified:
  if(!is.null(outdir)){
    # Checking if outdir exists:
    if(!dir.exists(outdir)){
      if(verbose){
        log_trace("Directory '", outdir, "' doesn't exist. Checking if it can be created.")
      }
      
      # If it's an actual directory, create it:
      if(!str_detect(outdir, "\\..*$")){
        dir.create(outdir)
        if(verbose){
          log_success("Directory '", outdir, "' created.")
        }
        
      # If it's a filename, return an error:
      } else{
        quit <- TRUE
        log_error("Output directory '", outdir, "' seems to be a filename.")
      }
    }
  #   - If there's no outdir specified, warn the user of the outdir used:
  } else {
    log_info("Outputting to '", dirname(gt3x_file), "'. Specify a directory in the 'outdir' parameter if you wish to change this.")
  }
  
  # If there are no errors:
  if(!quit){
    # Initializing runtime counter (with trace message):
    if(verbose){
      log_trace(paste0("Initializing runtime counter."))
    }
    
    startTime <- Sys.time()

    # Trace message:
    if(verbose){
      log_trace(paste0("Started processing file '", gt3x_file, "'."))
    }
    
    # Auxiliary variables;
    #   - Output directory:
    ifelse(is.null(outdir),
           assign("outdir", dirname(gt3x_file)),
           assign("outdir", outdir)) %>%
      # Don't print ifelse() results to log:
      invisible
    
    #   - Output file:
    assign("outfile",
           basename(gt3x_file) %>%
             # Trimming file extension out:
             str_sub(1, -6))
    
    # Trace message:
    if(verbose){
      log_trace(paste0("Using '", outdir, "' as the output directory and '", outfile, "' as the output filename."))
      log_trace(paste0("Attempting to extract contents from '.gt3x' file."))
    }
    
    # Extracting activity header from the 'info.txt' file and exporting content from 
    # the 'log.bin' file as CSV:
    header_csv(gt3x_file, outdir, verbose = verbose)
    save_accel(gt3x_file, outdir, verbose = verbose)

    # Trace message with elapsed time:
    if(verbose){
      log_trace(paste0("File '",
                       outfile,
                       ".gt3x' processed. Took ",
                       (Sys.time() - startTime) %>%
                         as.numeric %>%
                         round(2), 
                       " seconds."))
    }
  }
}